### ISSUE TITLE
401 errors from function app runtimes

### ISSUE THREAD

**Issue by braingle** [aws-samples/aws-iam-identity-center-sync-script#6]
Started seeing the 401 unauthorized errors. No updates or nothing has changed. 

Error:

EXCEPTION: Response status code does not indicate success: 401 (Unauthorized). Exception : Type : Microsoft.PowerShell.Commands.HttpResponseException Response : StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers: { Transfer-Encoding: chunked Strict-Transport-

Microsoft might have updated the graph api access fetch. Still looking into it. 

Thanks

**Comment by braingle** [comment]
It works by adding the role claims with one of the application  directory.read.write.al permissions and also updating graph api permissions Consent with Directory.ReadWrite.All

**Comment by braingle** [comment]
It works by adding the role claims with one of the application  directory.read.write.al permissions and also updating graph api permissions Consent with Directory.ReadWrite.All

**Comment by ajkeane-aws** [comment]
Thank you for reaching out on this.  I deployed the application today and received the same error.

To resolve it – I had to add a second permission to the Azure API – Synchronization.ReadWrite.All 

![api-permission](https://github.com/aws-samples/aws-iam-identity-center-sync-script/assets/67668465/77d06fa7-af00-4b1b-a748-3d4c306fbdb1)
https://learn.microsoft.com/en-us/graph/api/synchronization-serviceprincipal-put-synchronization?view=graph-rest-beta&tabs=http#permissions
