### ISSUE TITLE
Graph API permissions clarification

### ISSUE THREAD

**Issue by josemdav** [aws-samples/aws-iam-identity-center-sync-script#7]
The README mentions a permission called `Synchronization.ReadWrite.OwnedBy`, however, I don't find that API permission and instead `Synchronization.ReadWrite.All`, which I think can manage any application's synchronization configuration in the tenant. 

I think clarification is needed. Thanks

**Comment by ajkeane-aws** [comment]
Apologies - that was a typo. Updated the readme. It was correct in the blog link. Thank you for catching that.
